export enum MessageErrorCode {
    UNAUTHORIZED = 'UNAUTHORIZED',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR',
    INVALID_IMAGE = 'INVALID_IMAGE',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
}
